name: Build and Deploy React App

on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16.x # Change to the Node.js version you prefer
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn' # Cache Yarn packages to speed up subsequent runs

      - name: Install Yarn packages
        run: yarn install

      - name: Build
        run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
